Use page query over static query
xebia-france/tindev pull request #21
Opened 2021-02-01 15:42 UTC by blacroix

2021-02-02 03:16 UTC, avine requested changes

2021-02-02 03:16 UTC, avine commented on src/pages/play.tsx
> +  const [deck] = useState(() => buildDataset(data.allDataCsv.nodes));
`buildDataset` should be executed in `useEffect()`.
Because the function returns another dataset each time it is called.

2021-02-02 03:16 UTC, avine commented on src/pages/play.tsx
> +export const query = graphql`
Just to understand : when Gatsby find a GraphQL query exported by the page, the convention is to use it as data in the component ?

2021-02-02 03:16 UTC, avine commented on src/services/data.tsx
> -import { graphql, StaticQuery } from 'gatsby';
We should have keep the file and import things from it in the play page... no ?

2021-02-02 07:41 UTC, blacroix commented on src/pages/play.tsx
> +export const query = graphql`
Yes: https://www.gatsbyjs.com/docs/how-to/querying-data/page-query/

2021-02-02 07:41 UTC, blacroix commented on src/services/data.tsx
> -import { graphql, StaticQuery } from 'gatsby';
We can't we need a query in page to wire everything. See: https://www.gatsbyjs.com/docs/how-to/querying-data/page-query/

2021-02-02 07:42 UTC, blacroix commented on src/pages/play.tsx
> +export const query = graphql`
Yes! https://www.gatsbyjs.com/docs/how-to/querying-data/page-query/

2021-02-03 05:58 UTC, avine requested changes
The PR is OK.

Here's a small refactoring of `play.ts` to make things clearer:

```ts
import { graphql, navigate, PageProps } from 'gatsby';
import React, { useEffect, useState } from 'react';

import { Deck } from '../components/Deck/Deck';
import { Footer } from '../components/Footer/Footer';
import { Header } from '../components/Header/Header';
import { Layout } from '../components/Layout/Layout';
import { Page } from '../components/Page/Page';
import { Wave } from '../components/Wave/Wave';
import { Answer, DataItem } from '../services/data.model';
import { authorizeJoin } from '../services/security';
import buildDataset from '../services/utils/buildDataset';

const EXPECTED_COUNT = 8;

export const query = graphql`
  query PlayQuery {
    allDataCsv {
      nodes {
        question
        important
        response
      }
    }
  }`;

type PlayProps = PageProps & {
  data: {
    allDataCsv: {
      nodes: DataItem[];
    }
  }
}

const PlayPage = ({ data }: PlayProps) => {
  const [count, setCount] = useState(0);
  const [finish, setFinish] = useState(false);
  const [deck, setDeck] = useState<DataItem[]>([]);

  useEffect(() => {
    setDeck(buildDataset(data.allDataCsv.nodes));
  }, []);

  if (finish) {
    const isMatch = count >= EXPECTED_COUNT;
    if (isMatch) {
      authorizeJoin();
    }
    setTimeout(() => navigate(isMatch ? '/match' : '/nomatch'), 500);
  }

  const onAnswer: Answer = (item, answer, isLast) => {
    if (item.important && item.response === answer) {
      setCount(count + 1);
    }
    if (isLast) {
      setFinish(true);
    }
  };

  return (
    <Page>
      <Layout
        header={<Header withBackground={false}/>}
        footer={<Footer withBackground/>}
      >
        <Wave isSmall={finish}/>
        {deck.length > 0 && <Deck data={deck} onAnswer={onAnswer}/>}
      </Layout>
    </Page>
  );
};

export default PlayPage;
```

2021-02-03 05:58 UTC, avine commented on src/pages/play.tsx
> +  const [deck, setDeck] = useState([] as DataItem[]);
Prefer the syntax: `useState<DataItem[]>([]);`

2021-02-03 05:58 UTC, avine commented on src/services/utils/buildDataset.ts
> +  console.log('hi');
Oops ! Remove this... :)

2021-02-03 08:02 UTC, merged